### ISSUE TITLE
Outcome equation

### ISSUE THREAD

**Issue by ghost** [apoorvalal/aipwML#1]
Great package! Very helpful for quick DR computation using ML methods. Thanks.
I had one quick question: shouldn't the outcome regression include the treatment indicator along with the the covariates ? I didn't spend enough time on going through the back-end functions but if the treatment indicator is not included in the outcome regression as a feature, aren't we doing something similar to DML then? Many thanks.

**Comment by apoorvalal** [comment]
The outcome model [nonparametric regression of the response surface $E[Y | X=x]$)  is fit on subsets of the population defined by their treatment status, so including the treatment indicator is superfluous (it would be collinear with the intercept). 

For details, see [Imbens 2004](https://stat.columbia.edu/~gelman/stuff_for_blog/imbens.pdf#page=9) and subsequent DoubleML papers.
